/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The signed-in member */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me/courses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The signed-in member's list in personal rank order */
        get: operations["listMyCourses"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me/courses/{courseId}/rounds": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Rounds the member logged at one course, newest first
         * @description A course that is not on the member's list has no rounds.
         */
        get: operations["listMyCourseRounds"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/rankings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Every published ranking entry
         * @description Public and cacheable: responses carry an ETag; send it as If-None-Match to receive 304 when nothing changed. Send no Authorization header so shared caches can store it.
         */
        get: operations["listRankings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/course-search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Find courses by name
         * @description Catalog courses carry their id; other hits carry details to send back when adding the course.
         */
        get: operations["searchCourses"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The member directory, a page at a time */
        get: operations["listMembers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/members/{username}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Another member's list, read-only
         * @description Usernames match case-insensitively.
         */
        get: operations["getMemberList"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/client-config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Settings every client reads at launch
         * @description Apps older than the minimum version must ask the member to update.
         */
        get: operations["getClientConfig"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Me: {
            username: string;
            displayName: string;
        };
        ApiError: {
            error: components["schemas"]["ApiErrorBody"];
        };
        ApiErrorBody: {
            /**
             * @description Stable machine-readable code. Current values: bad_request, validation_failed, unauthenticated, username_invalid, not_found, course_not_found, not_on_list, round_not_found, member_not_found, payload_too_large, unsupported_media_type, search_unavailable, internal. New codes may appear; treat unknown codes by HTTP status.
             * @example not_on_list
             */
            code: string;
            /** @description Explanation suitable to show to the member. */
            message: string;
            /** @description Correlates the failure with server logs. */
            requestId: string;
            /** @description Per-field problems for validation_failed; otherwise null. */
            fields: components["schemas"]["FieldError"][] | null;
        };
        FieldError: {
            /** @description Dotted path of the invalid input, e.g. `q` or `course.name`. */
            path: string;
            message: string;
        };
        MyCourses: {
            /** @description The member's list in personal rank order. */
            courses: components["schemas"]["MyCourse"][];
        };
        MyCourse: {
            course: components["schemas"]["Course"];
            rank: number;
            played: number;
        };
        Course: {
            /** Format: uuid */
            id: string;
            name: string;
            /** @description Display location, e.g. `Arcadia, MI, USA`; null when unknown. */
            location: string | null;
            city: string | null;
            /** @description Two-letter state code for US courses. */
            state: string | null;
            country: string;
            logoUrl: string | null;
            websiteUrl: string | null;
            ranks: components["schemas"]["CourseRanks"];
        };
        CourseRanks: {
            world: number | null;
            usa: number | null;
            usaPublic: number | null;
            /** @description Rank on the Best-in-State list of the course's own state. */
            state: number | null;
        };
        Rounds: {
            /** @description Newest first. */
            rounds: components["schemas"]["Round"][];
        };
        Round: {
            /** Format: uuid */
            id: string;
            /** Format: date */
            playedOn: string;
        };
        Rankings: {
            entries: components["schemas"]["RankingEntry"][];
        };
        RankingEntry: {
            course: components["schemas"]["Course"];
            rank: number;
            /** @description Published list: world, usa, usa_public or state. New lists may appear. */
            type: string;
            /** @description List scope, e.g. WORLD, USA or a state code. */
            scope: string;
        };
        SearchResults: {
            /** @description At most 10, best match first. */
            results: components["schemas"]["SearchHit"][];
        };
        SearchHit: {
            /**
             * Format: uuid
             * @description Catalog course id when the hit is already in the catalog; null otherwise.
             */
            courseId: string | null;
            course: components["schemas"]["CourseDetails"];
            ranks: components["schemas"]["CourseRanks"];
        };
        /** @description A course described by its details, e.g. a search result not yet in the catalog. */
        CourseDetails: {
            name: string;
            location: string | null;
            city: string | null;
            state: string | null;
            country: string;
            logoUrl: string | null;
            websiteUrl: string | null;
        };
        Members: {
            members: components["schemas"]["Member"][];
            /** @description Pass as `cursor` for the next page; null on the last page. */
            nextCursor: string | null;
        };
        /** @description Another member's public projection; never an email or an id. */
        Member: {
            username: string;
            displayName: string;
        };
        MemberList: {
            member: components["schemas"]["Member"];
            courses: components["schemas"]["MemberCourse"][];
        };
        MemberCourse: {
            course: components["schemas"]["Course"];
            rank: number;
            onMyList: boolean;
        };
        ClientConfig: {
            minimumVersions: components["schemas"]["MinimumVersions"];
            /** Format: uri */
            privacyUrl: string;
            /** Format: uri */
            accountDeletionUrl: string;
        };
        /** @description Oldest app versions the API still supports; older builds must update. */
        MinimumVersions: {
            ios: string;
            android: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The member. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
            /** @description No valid session: `unauthenticated`. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description The Clerk account cannot use the app: `username_invalid`. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    listMyCourses: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The list. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MyCourses"];
                };
            };
            /** @description No valid session: `unauthenticated`. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description The Clerk account cannot use the app: `username_invalid`. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    listMyCourseRounds: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                courseId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The rounds. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Rounds"];
                };
            };
            /** @description Invalid parameters: `validation_failed`. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description No valid session: `unauthenticated`. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description The Clerk account cannot use the app: `username_invalid`. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    listRankings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All entries of all published lists. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Rankings"];
                };
            };
            /** @description Not modified since the ETag sent in If-None-Match. */
            304: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    searchCourses: {
        parameters: {
            query: {
                /** @description Course name, at least two characters. */
                q: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Up to ten hits, best first. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResults"];
                };
            };
            /** @description Invalid parameters: `validation_failed`. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description No valid session: `unauthenticated`. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description The Clerk account cannot use the app: `username_invalid`. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Course discovery is unavailable: `search_unavailable`. Retry later. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    listMembers: {
        parameters: {
            query?: {
                cursor?: string | null;
                /** @description Defaults to 50. */
                limit?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One page of members. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Members"];
                };
            };
            /** @description Invalid parameters: `validation_failed`. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description No valid session: `unauthenticated`. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description The Clerk account cannot use the app: `username_invalid`. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    getMemberList: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                username: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The member and their list, with on-my-list flags for the viewer. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberList"];
                };
            };
            /** @description No valid session: `unauthenticated`. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description The Clerk account cannot use the app: `username_invalid`. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description No such member: `member_not_found`. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    getClientConfig: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Client settings. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClientConfig"];
                };
            };
        };
    };
}
