/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The signed-in member */
        get: operations["getMe"];
        put?: never;
        post?: never;
        /**
         * Delete the member's account
         * @description Deletes the member's list and rounds, removes their name and email, and deletes the sign-in account. Courses they added stay in the shared catalog. Safe to retry: after a 502, call it again with the same token.
         */
        delete: operations["deleteMe"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me/courses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The signed-in member's list in personal rank order */
        get: operations["listMyCourses"];
        put?: never;
        /**
         * Add a course described by its details and log rounds
         * @description For search hits without a catalog id and courses typed in by the member. The course is matched against the catalog or created, placed at `rank` if new to the list, and `quantity` rounds are logged. Not idempotent: retrying after a lost response logs the rounds again.
         */
        post: operations["addCourse"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me/courses/{courseId}/rounds": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Rounds the member logged at one course, newest first
         * @description A course that is not on the member's list has no rounds.
         */
        get: operations["listMyCourseRounds"];
        put?: never;
        /**
         * Log rounds at a catalog course
         * @description Adds the course at the bottom of the list if needed. Not idempotent.
         */
        post: operations["logRounds"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me/courses/{courseId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Put a catalog course on the list
         * @description Adds the course at the bottom and logs one round when it has none. Repeating it changes nothing, so retrying is safe.
         */
        put: operations["addToList"];
        post?: never;
        /**
         * Take a course off the list with all its rounds
         * @description A 404 on retry means the course is already gone.
         */
        delete: operations["removeCourse"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me/courses/{courseId}/rank": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Move a course to a position on the list
         * @description The whole list is renumbered, including courses a client has filtered out.
         */
        put: operations["moveCourse"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me/courses/{courseId}/play-count": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Set how many rounds a course has
         * @description Lowering deletes the oldest rounds; raising logs rounds dated today; zero removes the course.
         */
        put: operations["setPlayCount"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me/rounds/{roundId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete one round
         * @description Deleting a course's last round takes the course off the list. A 404 on retry means the round is already gone.
         */
        delete: operations["deleteRound"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/rankings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Every published ranking entry
         * @description Public and cacheable: responses carry an ETag; send it as If-None-Match to receive 304 when nothing changed. Send no Authorization header so shared caches can store it.
         */
        get: operations["listRankings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/course-search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Find courses by name
         * @description Catalog courses carry their id; other hits carry details to send back when adding the course.
         */
        get: operations["searchCourses"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The member directory, a page at a time */
        get: operations["listMembers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/members/{username}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Another member's list, read-only
         * @description Usernames match case-insensitively.
         */
        get: operations["getMemberList"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/client-config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Settings every client reads at launch
         * @description Apps older than the minimum version must ask the member to update.
         */
        get: operations["getClientConfig"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Me: {
            username: string;
            displayName: string;
        };
        ApiError: {
            error: components["schemas"]["ApiErrorBody"];
        };
        ApiErrorBody: {
            /**
             * @description Stable machine-readable code. Current values: bad_request, validation_failed, us_state_required, unauthenticated, account_deleted, username_invalid, not_found, course_not_found, not_on_list, round_not_found, member_not_found, payload_too_large, unsupported_media_type, account_deletion_incomplete, search_unavailable, internal. New codes may appear; treat unknown codes by HTTP status.
             * @example not_on_list
             */
            code: string;
            /** @description Explanation suitable to show to the member. */
            message: string;
            /** @description Correlates the failure with server logs. */
            requestId: string;
            /** @description Per-field problems for validation_failed; otherwise null. */
            fields: components["schemas"]["FieldError"][] | null;
        };
        FieldError: {
            /** @description Dotted path of the invalid input, e.g. `q` or `course.name`. */
            path: string;
            message: string;
        };
        MyCourses: {
            /** @description The member's list in personal rank order. */
            courses: components["schemas"]["MyCourse"][];
        };
        MyCourse: {
            course: components["schemas"]["Course"];
            rank: number;
            played: number;
        };
        Course: {
            /** Format: uuid */
            id: string;
            name: string;
            /** @description Display location, e.g. `Arcadia, MI, USA`; null when unknown. */
            location: string | null;
            city: string | null;
            /** @description Two-letter state code for US courses. */
            state: string | null;
            country: string;
            logoUrl: string | null;
            websiteUrl: string | null;
            ranks: components["schemas"]["CourseRanks"];
        };
        CourseRanks: {
            world: number | null;
            usa: number | null;
            usaPublic: number | null;
            /** @description Rank on the Best-in-State list of the course's own state. */
            state: number | null;
        };
        Rounds: {
            /** @description Newest first. */
            rounds: components["schemas"]["Round"][];
        };
        Round: {
            /** Format: uuid */
            id: string;
            /** Format: date */
            playedOn: string;
        };
        AddedToList: {
            /** @description False when the course was already on the list. */
            added: boolean;
            /** @description The member's whole list after the change, read in the same transaction. */
            courses: components["schemas"]["MyCourse"][];
        };
        AddToListRequest: {
            /**
             * Format: date
             * @description Date played (YYYY-MM-DD) in the member's time zone. The server's date (UTC) when omitted, so clients should send it.
             */
            playedOn?: string | null;
        };
        AddedCourse: {
            /** Format: uuid */
            courseId: string;
            rank: number;
            /** @description The member's whole list after the change, read in the same transaction. */
            courses: components["schemas"]["MyCourse"][];
        };
        AddCourseRequest: {
            course: components["schemas"]["CourseDetailsRequest"];
            source: components["schemas"]["CourseSource"];
            /** @description Position for a course not yet on the list; the bottom when omitted. A course already on the list keeps its rank. */
            rank?: number | null;
            /** @description Rounds to log; 1 when omitted. */
            quantity?: number | null;
            /**
             * Format: date
             * @description Date played (YYYY-MM-DD) in the member's time zone. The server's date (UTC) when omitted, so clients should send it.
             */
            playedOn?: string | null;
        };
        CourseDetailsRequest: {
            name: string;
            location?: string | null;
            city?: string | null;
            /** @description Required, as a two-letter code, for U.S. courses whose location does not name the state. */
            state?: string | null;
            country: string;
            logoUrl?: string | null;
            websiteUrl?: string | null;
        };
        /**
         * @description `search`: a course search hit; `manual`: a course the member typed in (shared with everyone as a custom course).
         * @enum {string}
         */
        CourseSource: "search" | "manual";
        LoggedRounds: {
            /** @description Rounds logged. */
            added: number;
            /** @description The member's whole list after the change, read in the same transaction. */
            courses: components["schemas"]["MyCourse"][];
        };
        LogRoundsRequest: {
            /** @description Rounds to log; 1 when omitted. */
            quantity?: number | null;
            /**
             * Format: date
             * @description Date played (YYYY-MM-DD) in the member's time zone. The server's date (UTC) when omitted, so clients should send it.
             */
            playedOn?: string | null;
        };
        MovedCourse: {
            rank: number;
            /** @description The member's whole list after the change, read in the same transaction. */
            courses: components["schemas"]["MyCourse"][];
        };
        MoveCourseRequest: {
            /** @description Target position; past the end means the bottom. */
            rank: number;
        };
        PlayCount: {
            count: number;
            /** @description True when a count of zero removed the course from the list. */
            removed: boolean;
            /** @description The member's whole list after the change, read in the same transaction. */
            courses: components["schemas"]["MyCourse"][];
        };
        SetPlayCountRequest: {
            /** @description Zero removes the course from the list. Lowering deletes the oldest rounds. */
            count: number;
        };
        DeletedRound: {
            /** Format: uuid */
            courseId: string;
            /** @description True when it was the course's last round, which removes the course. */
            removedCourse: boolean;
            /** @description The member's whole list after the change, read in the same transaction. */
            courses: components["schemas"]["MyCourse"][];
        };
        Rankings: {
            entries: components["schemas"]["RankingEntry"][];
        };
        RankingEntry: {
            course: components["schemas"]["Course"];
            rank: number;
            /** @description Published list: world, usa, usa_public or state. New lists may appear. */
            type: string;
            /** @description List scope, e.g. WORLD, USA or a state code. */
            scope: string;
        };
        SearchResults: {
            /** @description At most 10, best match first. */
            results: components["schemas"]["SearchHit"][];
        };
        SearchHit: {
            /**
             * Format: uuid
             * @description Catalog course id when the hit is already in the catalog; null otherwise.
             */
            courseId: string | null;
            course: components["schemas"]["CourseDetails"];
            ranks: components["schemas"]["CourseRanks"];
        };
        /** @description A course described by its details, e.g. a search result not yet in the catalog. */
        CourseDetails: {
            name: string;
            location: string | null;
            city: string | null;
            state: string | null;
            country: string;
            logoUrl: string | null;
            websiteUrl: string | null;
        };
        Members: {
            members: components["schemas"]["Member"][];
            /** @description Pass as `cursor` for the next page; null on the last page. */
            nextCursor: string | null;
        };
        /** @description Another member's public projection; never an email or an id. */
        Member: {
            username: string;
            displayName: string;
        };
        MemberList: {
            member: components["schemas"]["Member"];
            courses: components["schemas"]["MemberCourse"][];
        };
        MemberCourse: {
            course: components["schemas"]["Course"];
            rank: number;
            onMyList: boolean;
        };
        ClientConfig: {
            minimumVersions: components["schemas"]["MinimumVersions"];
            /** Format: uri */
            privacyUrl: string;
            /** Format: uri */
            accountDeletionUrl: string;
        };
        /** @description Oldest app versions the API still supports; older builds must update. */
        MinimumVersions: {
            ios: string;
            android: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The member. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
            /** @description No valid session: `unauthenticated`, or `account_deleted` after the account was deleted. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description The Clerk account cannot use the app: `username_invalid`. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    deleteMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The account is deleted; sign the member out. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No valid session: `unauthenticated`, or `account_deleted` after the account was deleted. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description The Clerk account cannot use the app: `username_invalid`. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description The data is deleted but the sign-in account could not be: `account_deletion_incomplete`. Retry. */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    listMyCourses: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The list. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MyCourses"];
                };
            };
            /** @description No valid session: `unauthenticated`, or `account_deleted` after the account was deleted. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description The Clerk account cannot use the app: `username_invalid`. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    addCourse: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddCourseRequest"];
            };
        };
        responses: {
            /** @description The course and the updated list. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AddedCourse"];
                };
            };
            /** @description Invalid body: `validation_failed`, `us_state_required`, or `bad_request` for unreadable JSON. Also 413 `payload_too_large` above 32 KB and 415 `unsupported_media_type` without Content-Type: application/json. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description No valid session: `unauthenticated`, or `account_deleted` after the account was deleted. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description The Clerk account cannot use the app: `username_invalid`. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    listMyCourseRounds: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                courseId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The rounds. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Rounds"];
                };
            };
            /** @description Invalid parameters: `validation_failed`. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description No valid session: `unauthenticated`, or `account_deleted` after the account was deleted. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description The Clerk account cannot use the app: `username_invalid`. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    logRounds: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                courseId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LogRoundsRequest"];
            };
        };
        responses: {
            /** @description The updated list. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoggedRounds"];
                };
            };
            /** @description Invalid body: `validation_failed`, `us_state_required`, or `bad_request` for unreadable JSON. Also 413 `payload_too_large` above 32 KB and 415 `unsupported_media_type` without Content-Type: application/json. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description No valid session: `unauthenticated`, or `account_deleted` after the account was deleted. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description The Clerk account cannot use the app: `username_invalid`. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description No such catalog course: `course_not_found`. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    addToList: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                courseId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddToListRequest"];
            };
        };
        responses: {
            /** @description The updated list. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AddedToList"];
                };
            };
            /** @description Invalid body: `validation_failed`, `us_state_required`, or `bad_request` for unreadable JSON. Also 413 `payload_too_large` above 32 KB and 415 `unsupported_media_type` without Content-Type: application/json. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description No valid session: `unauthenticated`, or `account_deleted` after the account was deleted. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description The Clerk account cannot use the app: `username_invalid`. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description No such catalog course: `course_not_found`. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    removeCourse: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                courseId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The updated list. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MyCourses"];
                };
            };
            /** @description Invalid parameters: `validation_failed`. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description No valid session: `unauthenticated`, or `account_deleted` after the account was deleted. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description The Clerk account cannot use the app: `username_invalid`. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description The course is not on the list: `not_on_list`. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    moveCourse: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                courseId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MoveCourseRequest"];
            };
        };
        responses: {
            /** @description The course's new rank and the updated list. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MovedCourse"];
                };
            };
            /** @description Invalid body: `validation_failed`, `us_state_required`, or `bad_request` for unreadable JSON. Also 413 `payload_too_large` above 32 KB and 415 `unsupported_media_type` without Content-Type: application/json. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description No valid session: `unauthenticated`, or `account_deleted` after the account was deleted. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description The Clerk account cannot use the app: `username_invalid`. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description The course is not on the list: `not_on_list`. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    setPlayCount: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                courseId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetPlayCountRequest"];
            };
        };
        responses: {
            /** @description The count and the updated list. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayCount"];
                };
            };
            /** @description Invalid body: `validation_failed`, `us_state_required`, or `bad_request` for unreadable JSON. Also 413 `payload_too_large` above 32 KB and 415 `unsupported_media_type` without Content-Type: application/json. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description No valid session: `unauthenticated`, or `account_deleted` after the account was deleted. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description The Clerk account cannot use the app: `username_invalid`. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description The course is not on the list: `not_on_list`. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    deleteRound: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                roundId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The updated list. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeletedRound"];
                };
            };
            /** @description Invalid parameters: `validation_failed`. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description No valid session: `unauthenticated`, or `account_deleted` after the account was deleted. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description The Clerk account cannot use the app: `username_invalid`. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description No such round: `round_not_found`. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    listRankings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All entries of all published lists. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Rankings"];
                };
            };
            /** @description Not modified since the ETag sent in If-None-Match. */
            304: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    searchCourses: {
        parameters: {
            query: {
                /** @description Course name, at least two characters. */
                q: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Up to ten hits, best first. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResults"];
                };
            };
            /** @description Invalid parameters: `validation_failed`. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description No valid session: `unauthenticated`, or `account_deleted` after the account was deleted. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description The Clerk account cannot use the app: `username_invalid`. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Course discovery is unavailable: `search_unavailable`. Retry later. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    listMembers: {
        parameters: {
            query?: {
                cursor?: string | null;
                /** @description Defaults to 50. */
                limit?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One page of members. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Members"];
                };
            };
            /** @description Invalid parameters: `validation_failed`. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description No valid session: `unauthenticated`, or `account_deleted` after the account was deleted. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description The Clerk account cannot use the app: `username_invalid`. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    getMemberList: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                username: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The member and their list, with on-my-list flags for the viewer. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberList"];
                };
            };
            /** @description No valid session: `unauthenticated`, or `account_deleted` after the account was deleted. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description The Clerk account cannot use the app: `username_invalid`. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description No such member: `member_not_found`. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    getClientConfig: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Client settings. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClientConfig"];
                };
            };
        };
    };
}
