/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The signed-in member */
        get: operations["getMe"];
        put?: never;
        post?: never;
        /**
         * Delete the member's account
         * @description Deletes the member's list and rounds, removes their name and email, and deletes the sign-in account. Courses they added stay in the shared catalog. Safe to retry: after a 502, call it again with the same token. Works even for an account that other operations refuse with 403 `username_invalid` or 409 `username_taken`.
         */
        delete: operations["deleteMe"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me/courses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The signed-in member's list in personal rank order */
        get: operations["listMyCourses"];
        put?: never;
        /**
         * Add a course described by its details and log rounds
         * @description For search hits without a catalog id and courses typed in by the member. The course is matched against the catalog or created, placed at `rank` if new to the list, and `quantity` rounds are logged. Not idempotent: retrying after a lost response logs the rounds again.
         */
        post: operations["addCourse"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me/courses/{courseId}/rounds": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Rounds the member logged at one course, newest first
         * @description A course that is not on the member's list has no rounds.
         */
        get: operations["listMyCourseRounds"];
        put?: never;
        /**
         * Log rounds at a catalog course
         * @description Adds the course at the bottom of the list if needed. Not idempotent.
         */
        post: operations["logRounds"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me/courses/{courseId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Put a catalog course on the list
         * @description Adds the course at the bottom and logs one round when it has none. Repeating it changes nothing, so retrying is safe.
         */
        put: operations["addToList"];
        post?: never;
        /**
         * Take a course off the list with all its rounds
         * @description A 404 on retry means the course is already gone.
         */
        delete: operations["removeCourse"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me/courses/{courseId}/rank": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Move a course to a position on the list
         * @description The whole list is renumbered, including courses a client has filtered out.
         */
        put: operations["moveCourse"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me/courses/{courseId}/play-count": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Set how many rounds a course has
         * @description Lowering deletes the oldest rounds; raising logs rounds dated today; zero removes the course.
         */
        put: operations["setPlayCount"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me/rounds/{roundId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete one round
         * @description Deleting a course's last round takes the course off the list. A 404 on retry means the round is already gone.
         */
        delete: operations["deleteRound"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/rankings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Every published ranking entry
         * @description Public and cacheable: responses carry an ETag; send it as If-None-Match to receive 304 when nothing changed. Send no Authorization header so shared caches can store it.
         */
        get: operations["listRankings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/course-search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Find courses by name
         * @description Searches stored courses by default. Use source=external to explicitly search beyond the catalog. Catalog courses carry their id; other hits carry details to send back when adding the course.
         */
        get: operations["searchCourses"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The member's friends, a page at a time
         * @description Only accepted friends are listed; pending requests are in `listFriendRequests`.
         */
        get: operations["listMembers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/members/{username}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * A friend's list (or the member's own), read-only
         * @description Usernames match case-insensitively. A member who is not a friend is indistinguishable from no member.
         */
        get: operations["getMemberList"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/members/{username}/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * A friend's profile (or the member's own)
         * @description Header, stats, Top Four and, for a friend, how their ranking compares with the viewer's. A member who is not a friend is indistinguishable from no member.
         */
        get: operations["getMemberProfile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/members/{username}/rounds": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * A friend's timeline of rounds (or the member's own), a page at a time
         * @description Newest played first; undated rounds last. Dates and courses only.
         */
        get: operations["listMemberRounds"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/member-search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Find members by username to send a friend request
         * @description Returns usernames, display names and the viewer's relationship; never a list.
         */
        get: operations["searchMembers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me/friend-requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The member's pending friend requests, incoming and outgoing */
        get: operations["listFriendRequests"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me/friends/{username}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Send a friend request, or accept one from that member
         * @description Idempotent. If the other member already asked, this accepts and the two are friends; otherwise it sends a request. Usernames match case-insensitively.
         */
        put: operations["befriendMember"];
        post?: never;
        /** Remove a friend, cancel a request, or decline one */
        delete: operations["removeFriend"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/members/{username}/want-to-play": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * A friend's Want to play list (or the member's own)
         * @description Newest first. A member who is not a friend is indistinguishable from no member.
         */
        get: operations["listWantToPlay"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me/want-to-play/{courseId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Put a catalog course on the Want to play list
         * @description Played courses are allowed ("play it again"). Adding it again keeps the original date, so retrying is safe. Logging a round at the course takes it off the list.
         */
        put: operations["addWantToPlay"];
        post?: never;
        /**
         * Take a course off the Want to play list
         * @description Removing a course that is not on the list changes nothing, so retrying is safe.
         */
        delete: operations["removeWantToPlay"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/top-lists": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Every published list with the member's progress and their friends' */
        get: operations["listTopLists"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/top-lists/{type}/{scope}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * One published list as a checklist for the member and their friends
         * @description Every course in rank order with the member's rounds, Want to play, and the friends who played it.
         */
        get: operations["getTopList"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/feed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * What the member's friends did, newest first, a page at a time
         * @description Rounds logged long after they were played are collapsed into one backfill item per friend and day.
         */
        get: operations["getFeed"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/client-config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Settings every client reads at launch
         * @description Apps older than the minimum version must ask the member to update.
         */
        get: operations["getClientConfig"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Me: {
            username: string;
            displayName: string;
        };
        ApiError: {
            error: components["schemas"]["ApiErrorBody"];
        };
        ApiErrorBody: {
            /**
             * @description Stable machine-readable code. Current values: bad_request, validation_failed, us_state_required, unauthenticated, account_deleted, username_invalid, username_taken, not_found, course_not_found, not_on_list, round_not_found, member_not_found, friendship_not_found, top_list_not_found, payload_too_large, unsupported_media_type, account_deletion_incomplete, search_unavailable, internal. New codes may appear; treat unknown codes by HTTP status.
             * @example not_on_list
             */
            code: string;
            /** @description Explanation suitable to show to the member. */
            message: string;
            /** @description Correlates the failure with server logs. */
            requestId: string;
            /** @description Per-field problems for validation_failed; otherwise null. */
            fields: components["schemas"]["FieldError"][] | null;
        };
        FieldError: {
            /** @description Dotted path of the invalid input, e.g. `q` or `course.name`. */
            path: string;
            message: string;
        };
        MyCourses: {
            /** @description The member's list in personal rank order. */
            courses: components["schemas"]["MyCourse"][];
        };
        MyCourse: {
            course: components["schemas"]["Course"];
            rank: number;
            played: number;
        };
        Course: {
            /** Format: uuid */
            id: string;
            name: string;
            /** @description Display location, e.g. `Arcadia, MI, USA`; null when unknown. */
            location: string | null;
            city: string | null;
            /** @description Two-letter state code for US courses. */
            state: string | null;
            country: string;
            logoUrl: string | null;
            websiteUrl: string | null;
            ranks: components["schemas"]["CourseRanks"];
        };
        CourseRanks: {
            /** @description Golf Digest's World 100, which leaves out US courses (shown as International). */
            world: number | null;
            usa: number | null;
            usaPublic: number | null;
            /** @description Rank on the Best-in-State list of the course's own state. */
            state: number | null;
            /** @description GOLF Magazine's Top 100 Courses in the World, every country together (shown as World). */
            global: number | null;
        };
        Rounds: {
            /** @description Newest first. */
            rounds: components["schemas"]["Round"][];
        };
        Round: {
            /** Format: uuid */
            id: string;
            /** Format: date */
            playedOn: string;
        };
        AddedToList: {
            /** @description False when the course was already on the list. */
            added: boolean;
            /** @description The member's whole list after the change, read in the same transaction. */
            courses: components["schemas"]["MyCourse"][];
        };
        AddToListRequest: {
            /**
             * Format: date
             * @description Date played (YYYY-MM-DD) in the member's time zone. The server's date (UTC) when omitted, so clients should send it.
             */
            playedOn?: string | null;
        };
        AddedCourse: {
            /** Format: uuid */
            courseId: string;
            rank: number;
            /** @description Ids of the rounds just logged, so a client can offer Undo (`deleteRound` each one). */
            roundIds: string[];
            /** @description The member's whole list after the change, read in the same transaction. */
            courses: components["schemas"]["MyCourse"][];
        };
        AddCourseRequest: {
            course: components["schemas"]["CourseDetailsRequest"];
            source: components["schemas"]["CourseSource"];
            /** @description Position for a course not yet on the list; the bottom when omitted. A course already on the list keeps its rank. */
            rank?: number | null;
            /** @description Rounds to log; 1 when omitted. */
            quantity?: number | null;
            /**
             * Format: date
             * @description Date played (YYYY-MM-DD) in the member's time zone. The server's date (UTC) when omitted, so clients should send it.
             */
            playedOn?: string | null;
        };
        CourseDetailsRequest: {
            name: string;
            location?: string | null;
            city?: string | null;
            /** @description Required, as a two-letter code, for U.S. courses whose location does not name the state. */
            state?: string | null;
            country: string;
            logoUrl?: string | null;
            websiteUrl?: string | null;
        };
        /**
         * @description `search`: a course search hit; `manual`: a course the member typed in (shared with everyone as a custom course).
         * @enum {string}
         */
        CourseSource: "search" | "manual";
        LoggedRounds: {
            /** @description Rounds logged. */
            added: number;
            /** @description Ids of the rounds just logged, so a client can offer Undo (`deleteRound` each one). */
            roundIds: string[];
            /** @description The member's whole list after the change, read in the same transaction. */
            courses: components["schemas"]["MyCourse"][];
        };
        LogRoundsRequest: {
            /** @description Rounds to log; 1 when omitted. */
            quantity?: number | null;
            /**
             * Format: date
             * @description Date played (YYYY-MM-DD) in the member's time zone. The server's date (UTC) when omitted, so clients should send it.
             */
            playedOn?: string | null;
        };
        MovedCourse: {
            rank: number;
            /** @description The member's whole list after the change, read in the same transaction. */
            courses: components["schemas"]["MyCourse"][];
        };
        MoveCourseRequest: {
            /** @description Target position; past the end means the bottom. */
            rank: number;
        };
        PlayCount: {
            count: number;
            /** @description True when a count of zero removed the course from the list. */
            removed: boolean;
            /** @description The member's whole list after the change, read in the same transaction. */
            courses: components["schemas"]["MyCourse"][];
        };
        SetPlayCountRequest: {
            /** @description Zero removes the course from the list. Lowering deletes the oldest rounds. */
            count: number;
        };
        DeletedRound: {
            /** Format: uuid */
            courseId: string;
            /** @description True when it was the course's last round, which removes the course. */
            removedCourse: boolean;
            /** @description The member's whole list after the change, read in the same transaction. */
            courses: components["schemas"]["MyCourse"][];
        };
        Rankings: {
            entries: components["schemas"]["RankingEntry"][];
        };
        RankingEntry: {
            course: components["schemas"]["Course"];
            rank: number;
            /** @description Published list: global (GOLF Magazine, every country), world (Golf Digest, outside the US), usa, usa_public or state. New lists may appear. */
            type: string;
            /** @description List scope, e.g. WORLD, USA or a state code. */
            scope: string;
        };
        SearchResults: {
            /** @description At most 10, ordered alphabetically by course name, then location and id. */
            results: components["schemas"]["SearchHit"][];
            /** @description The requested page, starting at 1. */
            page: number;
            /** @description Results per page (10). */
            pageSize: number;
            /** @description Total matching courses after catalog resolution and deduplication. */
            total: number;
        };
        SearchHit: {
            /**
             * Format: uuid
             * @description Catalog course id when the hit is already in the catalog; null otherwise.
             */
            courseId: string | null;
            course: components["schemas"]["CourseDetails"];
            ranks: components["schemas"]["CourseRanks"];
        };
        /** @description A course described by its details, e.g. a search result not yet in the catalog. */
        CourseDetails: {
            name: string;
            location: string | null;
            city: string | null;
            state: string | null;
            country: string;
            logoUrl: string | null;
            websiteUrl: string | null;
        };
        Members: {
            members: components["schemas"]["Member"][];
            /** @description Pass as `cursor` for the next page; null on the last page. */
            nextCursor: string | null;
        };
        /** @description Another member's public projection; never an email or an id. */
        Member: {
            username: string;
            displayName: string;
        };
        MemberList: {
            member: components["schemas"]["Member"];
            courses: components["schemas"]["MemberCourse"][];
        };
        MemberCourse: {
            course: components["schemas"]["Course"];
            rank: number;
            onMyList: boolean;
            /** @description The member's rounds at this course. */
            played: number;
            /**
             * Format: date
             * @description The member's latest dated round here; null when none is dated.
             */
            lastPlayedOn: string | null;
            /** @description The viewer's own rank for this course; null when it is not on the viewer's list. */
            myRank: number | null;
        };
        Profile: {
            member: components["schemas"]["Member"];
            /** @description self or friends. New values may appear. */
            relationship: string;
            /**
             * Format: date
             * @description When the friendship was accepted; null on the viewer's own profile.
             */
            friendsSince: string | null;
            stats: components["schemas"]["ProfileStats"];
            /** @description The member's personal ranks 1-4 (fewer for a shorter list). */
            topFour: components["schemas"]["MemberCourse"][];
            comparison: components["schemas"]["RankComparison"];
        };
        ProfileStats: {
            courses: number;
            rounds: number;
            /** @description Rounds dated in the current calendar year (UTC). */
            roundsThisYear: number;
            friends: number;
        };
        /** @description How a member's ranking compares with the viewer's. Always present, so clients never decode a null object. */
        RankComparison: {
            /** @description Courses both members have ranked; null on the viewer's own profile. */
            inCommon: number | null;
            /** @description Share of shared-course pairs both members order the same way; null below three shared courses or on the viewer's own profile. */
            agreement: number | null;
            /** @description Courses whose positions differ most, largest first; at most one today, empty when there is nothing to compare. */
            biggestSplits: components["schemas"]["RankSplit"][];
        };
        /** @description The shared course whose positions differ most, relative to each list's length. */
        RankSplit: {
            course: components["schemas"]["Course"];
            myRank: number;
            theirRank: number;
        };
        Timeline: {
            /** @description Newest played first; undated rounds last. */
            rounds: components["schemas"]["TimelineRound"][];
            /** @description Pass as `cursor` for the next page; null on the last page. */
            nextCursor: string | null;
            /** @description Full round counts for every month with a round on this page, so a month split across pages shows its total from the first page. Newest month first; undated last. */
            months: components["schemas"]["TimelineMonth"][];
        };
        TimelineRound: {
            /** Format: uuid */
            id: string;
            course: components["schemas"]["Course"];
            /**
             * Format: date
             * @description Date played; null when the member did not record one.
             */
            playedOn: string | null;
            /** @description 1 for the member's first round at this course, 2 for the second; undated rounds count as earliest. */
            visit: number;
            /** @description The member's current personal rank for this course. */
            rank: number;
        };
        TimelineMonth: {
            /**
             * @description Year and month as YYYY-MM; null for the member's rounds without a date.
             * @example 2026-09
             */
            month: string | null;
            /** @description Every round the member logged in that month, including rounds on other pages. */
            rounds: number;
        };
        MemberSearchResults: {
            /** @description At most 20, usernames starting with the query first. */
            results: components["schemas"]["MemberRelationship"][];
        };
        MemberRelationship: {
            member: components["schemas"]["Member"];
            /** @description The viewer's relationship: none, friends, requested (the viewer asked; waiting for them) or incoming (they asked; the viewer can accept or decline). New values may appear. */
            relationship: string;
        };
        FriendRequests: {
            /** @description Members who asked the viewer, by username. */
            incoming: components["schemas"]["Member"][];
            /** @description Members the viewer asked, by username. */
            outgoing: components["schemas"]["Member"][];
        };
        WantToPlay: {
            /** @description Courses the member wants to play, newest first. */
            courses: components["schemas"]["WantToPlayEntry"][];
        };
        WantToPlayEntry: {
            course: components["schemas"]["Course"];
            /**
             * Format: date-time
             * @description When the member added it.
             */
            addedAt: string;
        };
        TopLists: {
            /** @description National lists first, then state lists by title. */
            lists: components["schemas"]["TopListProgress"][];
        };
        TopListProgress: {
            list: components["schemas"]["TopList"];
            /** @description Courses on the list the member has played. */
            mine: number;
            /** @description Friends who have played at least one course on it, most first. */
            friends: components["schemas"]["MemberProgress"][];
        };
        TopList: {
            /** @description global, world, usa, usa_public or state. New lists may appear. */
            type: string;
            /** @description GLOBAL, WORLD, USA, USA_PUBLIC or a two-letter state code. */
            scope: string;
            /** @description Display title, e.g. `World Top 100` or `Best in Georgia`. */
            title: string;
            size: number;
            /** @description Publisher, e.g. `GOLF Magazine`. */
            source: string;
            sourceYear: number;
        };
        MemberProgress: {
            member: components["schemas"]["Member"];
            played: number;
        };
        TopListDetail: {
            progress: components["schemas"]["TopListProgress"];
            /** @description In rank order. */
            entries: components["schemas"]["TopListEntry"][];
        };
        TopListEntry: {
            course: components["schemas"]["Course"];
            rank: number;
            /** @description The member's rounds at this course. */
            played: number;
            wantToPlay: boolean;
            /** @description Friends who have played it, by display name. */
            friendsPlayed: components["schemas"]["Member"][];
        };
        Feed: {
            /** @description Newest first. */
            items: components["schemas"]["FeedItem"][];
            /** @description Pass as `cursor` for the next page; null on the last page. */
            nextCursor: string | null;
        };
        FeedItem: {
            /** @description Stable across pages. */
            id: string;
            /** @description round (a friend logged a round) or backfill (rounds logged long after they were played, one item per member and day). New types may appear; skip ones you do not know. */
            type: string;
            /**
             * Format: date-time
             * @description When it happened: when the round was logged.
             */
            at: string;
            member: components["schemas"]["Member"];
            /** @description The round for a round item; up to four examples, one per course, for a backfill item. */
            rounds: components["schemas"]["TimelineRound"][];
            /** @description Rounds the item stands for: 1 for a round item, all of them for a backfill item. */
            count: number;
        };
        ClientConfig: {
            minimumVersions: components["schemas"]["MinimumVersions"];
            /** Format: uri */
            privacyUrl: string;
            /** Format: uri */
            accountDeletionUrl: string;
        };
        /** @description Oldest app versions the API still supports; older builds must update. */
        MinimumVersions: {
            ios: string;
            android: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The member. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
            /** @description No valid session: `unauthenticated`, or `account_deleted` after the account was deleted. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description The Clerk account cannot use the app: `username_invalid`. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Another member holds the Clerk account's username: `username_taken`. Choose a different username. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    deleteMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The account is deleted; sign the member out. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No valid session: `unauthenticated`, or `account_deleted` after the account was deleted. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Not returned since account deletion stopped provisioning the member; kept so existing clients still compile. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description The data is deleted but the sign-in account could not be: `account_deletion_incomplete`. Retry. */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    listMyCourses: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The list. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MyCourses"];
                };
            };
            /** @description No valid session: `unauthenticated`, or `account_deleted` after the account was deleted. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description The Clerk account cannot use the app: `username_invalid`. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Another member holds the Clerk account's username: `username_taken`. Choose a different username. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    addCourse: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddCourseRequest"];
            };
        };
        responses: {
            /** @description The course and the updated list. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AddedCourse"];
                };
            };
            /** @description Invalid body: `validation_failed`, `us_state_required`, or `bad_request` for unreadable JSON. Also 413 `payload_too_large` above 32 KB and 415 `unsupported_media_type` without Content-Type: application/json. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description No valid session: `unauthenticated`, or `account_deleted` after the account was deleted. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description The Clerk account cannot use the app: `username_invalid`. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Another member holds the Clerk account's username: `username_taken`. Choose a different username. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    listMyCourseRounds: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                courseId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The rounds. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Rounds"];
                };
            };
            /** @description Invalid parameters: `validation_failed`. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description No valid session: `unauthenticated`, or `account_deleted` after the account was deleted. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description The Clerk account cannot use the app: `username_invalid`. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Another member holds the Clerk account's username: `username_taken`. Choose a different username. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    logRounds: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                courseId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LogRoundsRequest"];
            };
        };
        responses: {
            /** @description The updated list. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoggedRounds"];
                };
            };
            /** @description Invalid body: `validation_failed`, `us_state_required`, or `bad_request` for unreadable JSON. Also 413 `payload_too_large` above 32 KB and 415 `unsupported_media_type` without Content-Type: application/json. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description No valid session: `unauthenticated`, or `account_deleted` after the account was deleted. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description The Clerk account cannot use the app: `username_invalid`. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description No such catalog course: `course_not_found`. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Another member holds the Clerk account's username: `username_taken`. Choose a different username. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    addToList: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                courseId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddToListRequest"];
            };
        };
        responses: {
            /** @description The updated list. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AddedToList"];
                };
            };
            /** @description Invalid body: `validation_failed`, `us_state_required`, or `bad_request` for unreadable JSON. Also 413 `payload_too_large` above 32 KB and 415 `unsupported_media_type` without Content-Type: application/json. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description No valid session: `unauthenticated`, or `account_deleted` after the account was deleted. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description The Clerk account cannot use the app: `username_invalid`. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description No such catalog course: `course_not_found`. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Another member holds the Clerk account's username: `username_taken`. Choose a different username. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    removeCourse: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                courseId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The updated list. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MyCourses"];
                };
            };
            /** @description Invalid parameters: `validation_failed`. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description No valid session: `unauthenticated`, or `account_deleted` after the account was deleted. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description The Clerk account cannot use the app: `username_invalid`. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description The course is not on the list: `not_on_list`. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Another member holds the Clerk account's username: `username_taken`. Choose a different username. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    moveCourse: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                courseId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MoveCourseRequest"];
            };
        };
        responses: {
            /** @description The course's new rank and the updated list. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MovedCourse"];
                };
            };
            /** @description Invalid body: `validation_failed`, `us_state_required`, or `bad_request` for unreadable JSON. Also 413 `payload_too_large` above 32 KB and 415 `unsupported_media_type` without Content-Type: application/json. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description No valid session: `unauthenticated`, or `account_deleted` after the account was deleted. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description The Clerk account cannot use the app: `username_invalid`. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description The course is not on the list: `not_on_list`. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Another member holds the Clerk account's username: `username_taken`. Choose a different username. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    setPlayCount: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                courseId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetPlayCountRequest"];
            };
        };
        responses: {
            /** @description The count and the updated list. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayCount"];
                };
            };
            /** @description Invalid body: `validation_failed`, `us_state_required`, or `bad_request` for unreadable JSON. Also 413 `payload_too_large` above 32 KB and 415 `unsupported_media_type` without Content-Type: application/json. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description No valid session: `unauthenticated`, or `account_deleted` after the account was deleted. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description The Clerk account cannot use the app: `username_invalid`. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description The course is not on the list: `not_on_list`. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Another member holds the Clerk account's username: `username_taken`. Choose a different username. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    deleteRound: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                roundId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The updated list. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeletedRound"];
                };
            };
            /** @description Invalid parameters: `validation_failed`. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description No valid session: `unauthenticated`, or `account_deleted` after the account was deleted. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description The Clerk account cannot use the app: `username_invalid`. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description No such round: `round_not_found`. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Another member holds the Clerk account's username: `username_taken`. Choose a different username. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    listRankings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All entries of all published lists. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Rankings"];
                };
            };
            /** @description Not modified since the ETag sent in If-None-Match. */
            304: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    searchCourses: {
        parameters: {
            query: {
                /** @description Defaults to catalog (stored courses only). Request external explicitly to discover courses beyond the catalog. */
                source?: "catalog" | "external" | null;
                /** @description Page number, starting at 1. Defaults to 1; each page contains at most 10 hits. */
                page?: number | null;
                /** @description Course name, at least two characters. */
                q: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description An alphabetical page of up to ten hits with the total match count. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResults"];
                };
            };
            /** @description Invalid parameters: `validation_failed`. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description No valid session: `unauthenticated`, or `account_deleted` after the account was deleted. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description The Clerk account cannot use the app: `username_invalid`. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Another member holds the Clerk account's username: `username_taken`. Choose a different username. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Course discovery is unavailable: `search_unavailable`. Retry later. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    listMembers: {
        parameters: {
            query?: {
                cursor?: string | null;
                /** @description Defaults to 50. */
                limit?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One page of members. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Members"];
                };
            };
            /** @description Invalid parameters: `validation_failed`. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description No valid session: `unauthenticated`, or `account_deleted` after the account was deleted. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description The Clerk account cannot use the app: `username_invalid`. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Another member holds the Clerk account's username: `username_taken`. Choose a different username. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    getMemberList: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                username: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The member and their list, with on-my-list flags for the viewer. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberList"];
                };
            };
            /** @description No valid session: `unauthenticated`, or `account_deleted` after the account was deleted. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description The Clerk account cannot use the app: `username_invalid`. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description No such member, or not a friend: `member_not_found`. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Another member holds the Clerk account's username: `username_taken`. Choose a different username. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    getMemberProfile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                username: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The profile. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Profile"];
                };
            };
            /** @description No valid session: `unauthenticated`, or `account_deleted` after the account was deleted. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description The Clerk account cannot use the app: `username_invalid`. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description No such member, or not a friend: `member_not_found`. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Another member holds the Clerk account's username: `username_taken`. Choose a different username. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    listMemberRounds: {
        parameters: {
            query?: {
                /** @description `nextCursor` from the previous page. */
                cursor?: string | null;
                /** @description Defaults to 30. */
                limit?: number | null;
            };
            header?: never;
            path: {
                username: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One page of rounds. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Timeline"];
                };
            };
            /** @description Invalid parameters or an unusable `cursor`: `validation_failed`. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description No valid session: `unauthenticated`, or `account_deleted` after the account was deleted. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description The Clerk account cannot use the app: `username_invalid`. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description No such member, or not a friend: `member_not_found`. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Another member holds the Clerk account's username: `username_taken`. Choose a different username. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    searchMembers: {
        parameters: {
            query: {
                /** @description Text in the username, at least three characters. */
                q: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Matching members. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberSearchResults"];
                };
            };
            /** @description Invalid parameters: `validation_failed`. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description No valid session: `unauthenticated`, or `account_deleted` after the account was deleted. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description The Clerk account cannot use the app: `username_invalid`. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Another member holds the Clerk account's username: `username_taken`. Choose a different username. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    listFriendRequests: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Pending requests. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FriendRequests"];
                };
            };
            /** @description No valid session: `unauthenticated`, or `account_deleted` after the account was deleted. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description The Clerk account cannot use the app: `username_invalid`. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Another member holds the Clerk account's username: `username_taken`. Choose a different username. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    befriendMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                username: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The relationship afterwards: requested or friends. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberRelationship"];
                };
            };
            /** @description The member's own username: `validation_failed`. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description No valid session: `unauthenticated`, or `account_deleted` after the account was deleted. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description The Clerk account cannot use the app: `username_invalid`. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description No such member: `member_not_found`. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Another member holds the Clerk account's username: `username_taken`. Choose a different username. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    removeFriend: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                username: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Nothing is left between the two members. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No valid session: `unauthenticated`, or `account_deleted` after the account was deleted. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description The Clerk account cannot use the app: `username_invalid`. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description No such member: `member_not_found`; nothing between the two: `friendship_not_found`. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Another member holds the Clerk account's username: `username_taken`. Choose a different username. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    listWantToPlay: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                username: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The Want to play list. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WantToPlay"];
                };
            };
            /** @description No valid session: `unauthenticated`, or `account_deleted` after the account was deleted. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description The Clerk account cannot use the app: `username_invalid`. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description No such member, or not a friend: `member_not_found`. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Another member holds the Clerk account's username: `username_taken`. Choose a different username. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    addWantToPlay: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                courseId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The member's Want to play list afterwards. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WantToPlay"];
                };
            };
            /** @description Invalid parameters: `validation_failed`. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description No valid session: `unauthenticated`, or `account_deleted` after the account was deleted. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description The Clerk account cannot use the app: `username_invalid`. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description No such catalog course: `course_not_found`. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Another member holds the Clerk account's username: `username_taken`. Choose a different username. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    removeWantToPlay: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                courseId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The member's Want to play list afterwards. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WantToPlay"];
                };
            };
            /** @description Invalid parameters: `validation_failed`. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description No valid session: `unauthenticated`, or `account_deleted` after the account was deleted. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description The Clerk account cannot use the app: `username_invalid`. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Another member holds the Clerk account's username: `username_taken`. Choose a different username. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    listTopLists: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Every list, national first. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TopLists"];
                };
            };
            /** @description No valid session: `unauthenticated`, or `account_deleted` after the account was deleted. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description The Clerk account cannot use the app: `username_invalid`. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Another member holds the Clerk account's username: `username_taken`. Choose a different username. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    getTopList: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                type: string;
                scope: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The list. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TopListDetail"];
                };
            };
            /** @description No valid session: `unauthenticated`, or `account_deleted` after the account was deleted. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description The Clerk account cannot use the app: `username_invalid`. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description No published list with that type and scope: `top_list_not_found`. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Another member holds the Clerk account's username: `username_taken`. Choose a different username. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    getFeed: {
        parameters: {
            query?: {
                /** @description `nextCursor` from the previous page. */
                cursor?: string | null;
                /** @description Defaults to 30. */
                limit?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One page of the feed. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Feed"];
                };
            };
            /** @description Invalid parameters or an unusable `cursor`: `validation_failed`. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description No valid session: `unauthenticated`, or `account_deleted` after the account was deleted. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description The Clerk account cannot use the app: `username_invalid`. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Another member holds the Clerk account's username: `username_taken`. Choose a different username. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    getClientConfig: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Client settings. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClientConfig"];
                };
            };
        };
    };
}
